# Generated by Django 3.2 on 2021-05-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=500)),
                ('imageUrl', models.URLField(blank=True)),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('version', models.IntegerField()),
                ('file', models.FileField(upload_to='media/tmp')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('document', models.TextField()),
                ('code', models.TextField()),
                ('contributor', models.EmailField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
        ),
    ]
